dist: trusty

language: node_js

install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.375.sh
  - chmod +x linux-install-1.9.0.375.sh
  - sudo ./linux-install-1.9.0.375.sh

script:
  - if [[ $CANARY_CLOJURESCRIPT_REV && ${CANARY_CLOJURESCRIPT_REV-x} ]]; then DEPS="{:deps {org.clojure/clojurescript {:git/url \"https://github.com/clojure/clojurescript\" :sha \"${CANARY_CLOJURESCRIPT_REV}\"}}}"; fi
  - clojure -Sdeps "${DEPS:-{}}" -A:test
